name: Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-python@v5
        with:
          python-version: 3.13
          cache: pip

      - uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: npm

      - name: Install dev dependencies
        run: make install-dev

      - name: Run spell check
        run: make check-spelling
