name: Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  spellcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - name: Install dev dependencies
        run: make install-dev

      - name: Run spell check
        run: make check-spelling
